### ISSUE TITLE
Need a launcher icon

### ISSUE THREAD

**Issue by stonepiersma** [KayFishandChips/CIS-163-Final-Project#6]
Hope this one is self explanatory

**Comment by Kloranthy** [comment]
![sdl-48](https://cloud.githubusercontent.com/assets/11448054/7258234/1c2590cc-e829-11e4-9685-039e6c059480.png)
what do you think?

**Comment by stonepiersma** [comment]
Color should match that of the app. I think this is off a bit. Instead of
an oval in the background, maybe a dollar sign in one corner and one of
those graduation hats in the corner diagonally opposite it? Would tie it in
to the main theme more that way. Also need to make sure its appropriately
large to accommodate multiple screen sizes

**Comment by Kloranthy** [comment]
![sdl-48-new](https://cloud.githubusercontent.com/assets/11448054/7259157/704063ca-e82f-11e4-987d-1f9da0b840f4.png)
I can't draw grad hats to save my life...

**Comment by stonepiersma** [comment]
Lol I can find one on Google if you want? Theres lots of public use images
on Google

**Comment by stonepiersma** [comment]
![app_icon](https://cloud.githubusercontent.com/assets/9088531/7263615/141ba736-e851-11e4-8eda-59af57f4c747.png) Having a vector graphics program like Inkscape (free) is helpful. What says you to this?

**Comment by stonepiersma** [comment]
http://developer.android.com/design/style/iconography.html#launcher anyone got fancy skills to make our icon have 'depth' as wanted by Google for Play store publishing?

**Comment by stonepiersma** [comment]
![icon](https://cloud.githubusercontent.com/assets/9088531/7266083/68f60a6e-e872-11e4-9568-1d8d2addda57.png)
This is to be uploaded for the Google Play store. It is also now set as the launcher icon so we can get it posted. We can change it later if necessary, but at least we have something now if need be
