### ISSUE TITLE
Should hide the activity name displayed at the top of each activity (excluding start activity)

### ISSUE THREAD

**Issue by stonepiersma** [KayFishandChips/CIS-163-Final-Project#8]

**Comment by Kloranthy** [comment]
should I set them all to Student Discount Locator?

**Comment by stonepiersma** [comment]
If we can make them disappear entirely that would be preferable. Barring
that, yes, set them all to say Student Discount Locator

**Comment by Kloranthy** [comment]
![screenshot_2015-04-21-20-28-14](https://cloud.githubusercontent.com/assets/11448054/7265280/1d85de18-e865-11e4-9c3f-f95593de1045.png)
looks kinda blank without an action bar...

**Comment by stonepiersma** [comment]
Yeah kinda does. Can you make it say like "Find a discount!" or something
similar?

**Comment by stonepiersma** [comment]
Also what magic did you do to hide the bar? Reference link? I tried for
days and couldn't make it go away...

**Comment by stonepiersma** [comment]
Closing issue. Josh edited activity titles
